# templates/database-secretproviderclass.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "secret-sharer-app.fullname" . }}-db-init-spc # Distinct name for DB SPC
  labels:
    {{- include "secret-sharer-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  provider: azure
  parameters:
    usePodIdentity: "false" # Required for Workload Identity
    useVMManagedIdentity: "false" # Not using VM identity directly
    # Uses the Client ID of the *Database* User Assigned Managed Identity
    clientID: {{ .Values.database.serviceAccount.azureClientId | quote }}
    keyvaultName: {{ .Values.backend.keyVault.name | quote }} # Assuming same Key Vault for all secrets
    cloudName: "" # Defaults to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: {{ .Values.database.keyVault.secrets.initPassword }}
          objectType: secret
        - |
          objectName: {{ .Values.backend.keyVault.secrets.dbUser }}
          objectType: secret
        - |
          objectName: {{ .Values.backend.keyVault.secrets.dbPassword }}
          objectType: secret

    tenantId: {{ .Values.backend.keyVault.tenantId | quote }} # Assuming same tenant ID