# templates/database-serviceaccount.yaml
{{- if .Values.database.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secret-sharer-app.databaseServiceAccountName" . }} # We will define this helper next
  labels:
    {{- include "secret-sharer-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  annotations:
    # This annotation links the SA to the Azure User Assigned Managed Identity via Workload Identity
    azure.workload.identity/client-id: {{ .Values.database.serviceAccount.azureClientId | quote }}
    {{- with .Values.database.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true # Required for Workload Identity token projection
{{- end }}