# templates/database-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "secret-sharer-app.fullname" . }}-db-init-script
  labels:
    {{- include "secret-sharer-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
data:
  # The key name here (e.g., init-db.sh) will become the filename when mounted as a volume
  init-db.sh: |-
    {{- .Files.Get "scripts/init-db.sh" | nindent 4 }}