# templates/serviceaccount.yaml
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "secret-sharer-app.fullname" .) }} # Uses the name from values.yaml
  labels:
    {{- include "secret-sharer-app.labels" . | nindent 4 }}
  annotations:
    # Annotation for Azure Workload Identity
    azure.workload.identity/client-id: {{ .Values.backend.keyVault.userAssignedIdentityClientID | quote }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
automountServiceAccountToken: true
{{- end -}}