name: Calling Workflow

on:
  workflow_dispatch:

jobs:
  deploy_dev:
    name: Deploy to Dev
    uses: ./.github/workflows/reuse.yml
    with:
      environment: shared
    secrets:
      PASSWORD: ${{ secrets.CLIENTID_ART_PUSH }}
      
  deploy_prod:
    name: Deploy to Prod
    needs: deploy_dev
    uses: ./.github/workflows/reuse.yml
    with:
      environment: shared
    secrets:
      PASSWORD: ${{ secrets.CLIENTID_ART_PUSH }}