# Template for deploying shared infrastructure (ACR) using Azure Bicep templates
# This workflow is triggered manually to deploy the Azure Container Registry
name: 'CD - Shared Infrastructure (ACR)'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      acrName:
        description: 'Azure Container Registry name'
        required: true
        type: string

jobs:
  what-if-analysis:
    name: 'What-If Analysis'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: ${{ inputs.environment }}
    outputs:
      what-if-results: ${{ steps.whatif.outputs.results }}
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
            
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.UAMI_SHARED_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run What-If Analysis'
        id: whatif
        env:
          SHARED_RG_NAME: ${{ secrets.SHARED_RG_NAME }}
        run: |
          echo "Running what-if analysis for resource group: ${{ env.SHARED_RG_NAME }}"
          
          # Run what-if analysis
          whatif_output=$(az deployment group what-if \
            --resource-group "${{ env.SHARED_RG_NAME }}" \
            --template-file ./infra/shared-infra.bicep \
            --parameters acrName="${{ inputs.acrName }}" \
                         resourceLocation="${{ vars.AZURE_REGION }}" \
                         tags='{"environment":"${{ inputs.environment }}","project":"${{ vars.PROJECT_NAME }}","owner":"GitHubActions","runId":"${{ github.run_id }}"}' \
            --result-format FullResourcePayloads 2>&1)
          
          echo "What-if analysis completed"
          echo "$whatif_output"
          
          # Save results for next job
          echo "results<<EOF" >> $GITHUB_OUTPUT
          echo "$whatif_output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 'Create What-If Summary'
        env:
          SHARED_RG_NAME: ${{ secrets.SHARED_RG_NAME }}
        run: |
          cat << 'EOF' >> $GITHUB_STEP_SUMMARY
          ## 🔍 What-If Analysis Results
          
          **Target Resource Group:** `${{ env.SHARED_RG_NAME }}`
          **ACR Name:** `${{ inputs.acrName }}`
          **Environment:** `${{ inputs.environment }}`
          
          ### Changes Preview:
          ```
          ${{ steps.whatif.outputs.results }}
          ```
          
          **Next Step:** Review the changes above and proceed to the deployment job if everything looks correct.
          EOF

  manual-approval:
    name: 'Manual Approval Required'
    runs-on: ubuntu-latest
    needs: what-if-analysis
    environment: 
      name: ${{ inputs.environment }}-approval
      url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: 'Display What-If Results for Approval'
        run: |
          echo "Please review the what-if analysis results:"
          echo "${{ needs.what-if-analysis.outputs.what-if-results }}"
          echo ""
          echo "If the changes look correct, approve this deployment to proceed."

  deploy-shared-infrastructure:
    name: 'Deploy Shared Infrastructure'
    runs-on: ubuntu-latest
    needs: [what-if-analysis, manual-approval]
    permissions:
      contents: read
      id-token: write
    environment: ${{ inputs.environment }}
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
            
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.UAMI_SHARED_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy Shared Infrastructure bicep template'
        env:
          AZURE_PREFIX_SECRET: ${{ secrets.AZURE_PREFIX }}
          SHARED_RG_NAME: ${{ secrets.SHARED_RG_NAME }}
        run: |
          echo "Deploying to resource group: ${{ env.SHARED_RG_NAME }}"
          
          az deployment group create \
            --name "shared-infra-${{ inputs.environment }}-${{ github.run_id }}" \
            --resource-group "${{ env.SHARED_RG_NAME }}" \
            --template-file ./infra/shared-infra.bicep \
            --parameters acrName="${{ inputs.acrName }}" \
                         resourceLocation="${{ vars.AZURE_REGION }}" \
                         tags='{"environment":"${{ inputs.environment }}","project":"${{ vars.PROJECT_NAME }}","owner":"GitHubActions","runId":"${{ github.run_id }}"}' \
            --verbose

      - name: 'Deployment Summary'
        env:
          SHARED_RG_NAME: ${{ secrets.SHARED_RG_NAME }}
        run: |
          echo "✅ Deployment completed successfully!"
          echo "Resource Group: ${{ env.SHARED_RG_NAME }}"
          echo "ACR Name: ${{ inputs.acrName }}"
          echo "Environment: ${{ inputs.environment }}"