# Template for deploying shared infrastructure (ACR) using Azure Bicep templates
# This workflow is triggered manually to deploy the Azure Container Registry
name: 'CD - Shared Infrastructure (ACR)'

on:
  workflow_dispatch:
jobs:
  what-if-analysis:
    name: 'What-If Analysis'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      what-if-results: ${{ steps.whatif.outputs.results }}
      has-changes: ${{ steps.check-changes.outputs.has-changes }}
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENTID_ART_PUSH }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run What-If Analysis'
        id: whatif
        env:
          SHARED_RG_NAME: ${{ vars.SHARED_RG_NAME }}
        run: |
          echo "Running what-if analysis for resource group: ${{ env.SHARED_RG_NAME }}"
          echo "ACR Name: ${{ vars.ACR_NAME }}"
            # Run what-if analysis
          whatif_output=$(az deployment group what-if \
            --resource-group "${{ env.SHARED_RG_NAME }}" \
            --template-file ./infra/shared-infra.bicep \
            --parameters acrName="${{ vars.ACR_NAME }}" \
                         resourceLocation="${{ vars.AZURE_REGION }}" \
                         tags='{"environment":"shared","project":"${{ vars.PROJECT_NAME }}","owner":"GitHubActions"}' \
            --result-format FullResourcePayloads 2>&1)
          
          echo "What-if analysis completed"
          echo "$whatif_output"
          
          # Save results for next job
          echo "results<<EOF" >> $GITHUB_OUTPUT
          echo "$whatif_output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 'Check for Changes'
        id: check-changes
        run: |
          # Check if what-if output contains any changes
          whatif_output="${{ steps.whatif.outputs.results }}"
          
          # Look for indicators of changes in the what-if output
          if echo "$whatif_output" | grep -q "No changes detected"; then
            echo "No changes detected in what-if analysis"
            echo "has-changes=false" >> $GITHUB_OUTPUT
          elif echo "$whatif_output" | grep -E -q "(Create|Modify|Delete|Deploy)"; then
            echo "Changes detected in what-if analysis"
            echo "has-changes=true" >> $GITHUB_OUTPUT
          else
            # Default to true if we can't determine
            echo "Unable to determine changes, defaulting to deployment"
            echo "has-changes=true" >> $GITHUB_OUTPUT
          fi

      - name: 'Create What-If Summary'
        env:
          SHARED_RG_NAME: ${{ vars.SHARED_RG_NAME }}
        run: |
          if [[ "${{ steps.check-changes.outputs.has-changes }}" == "true" ]]; then
            deployment_status="🚀 **Deployment Required** - Changes detected"
          else
            deployment_status="✅ **No Deployment Needed** - No changes detected"
          fi
          
          cat << EOF >> $GITHUB_STEP_SUMMARY
          ## 🔍 What-If Analysis Results
            **Target Resource Group:** \`${{ env.SHARED_RG_NAME }}\`
          **ACR Name:** \`${{ vars.ACR_NAME }}\`
          **Environment:** \`shared\`
          
          ### Status: $deployment_status
          
          ### Changes Preview:
          \`\`\`
          ${{ steps.whatif.outputs.results }}
          \`\`\`
          
          EOF
          
          if [[ "${{ steps.check-changes.outputs.has-changes }}" == "true" ]]; then
            echo "**Next Step:** Review the changes above and approve the deployment job to proceed." >> $GITHUB_STEP_SUMMARY
          else
            echo "**Next Step:** No action required. Infrastructure is already up to date." >> $GITHUB_STEP_SUMMARY
          fi

  deploy-shared-infrastructure:
    name: 'Deploy Shared Infrastructure'
    runs-on: ubuntu-latest
    needs: what-if-analysis
    if: needs.what-if-analysis.outputs.has-changes == 'true'
    permissions:
      contents: read
      id-token: write
    environment: shared-infra
    steps:
      - name: 'Display Approved Plan'
        run: |
          echo "✅ Approval granted. Displaying approved changes before deployment."
          echo ""
          echo "🔍 WHAT-IF ANALYSIS CHANGES:"
          echo "================================"
          echo "${{ needs.what-if-analysis.outputs.what-if-results }}"
          echo "================================"
          echo ""
          echo "📋 DEPLOYMENT DETAILS:"
          echo "• Target Resource Group: ${{ vars.SHARED_RG_NAME }}"
          echo "• ACR Name: ${{ vars.ACR_NAME }}"
          echo "• Environment: shared"

      - name: 'Checkout Code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
            
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ClientID_Art_Cont }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy Shared Infrastructure bicep template'
        env:
          SHARED_RG_NAME: ${{ vars.SHARED_RG_NAME }}
        run: |
          echo "Deploying to resource group: ${{ env.SHARED_RG_NAME }}"
          
          az deployment group create \
            --name "shared-infra-shared-${{ github.run_id }}" \
            --resource-group "${{ env.SHARED_RG_NAME }}" \
            --template-file ./infra/shared-infra.bicep \
            --parameters acrName="${{ vars.ACR_NAME }}" \
                         resourceLocation="${{ vars.AZURE_REGION }}" \
                         tags='{"environment":"shared","project":"${{ vars.PROJECT_NAME }}","owner":"GitHubActions","runId":"${{ github.run_id }}"}' \
            --verbose

      - name: 'Deployment Summary'
        env:
          SHARED_RG_NAME: ${{ vars.SHARED_RG_NAME }}
        run: |          
          echo "✅ Deployment completed successfully!"
          echo "Resource Group: ${{ env.SHARED_RG_NAME }}"
          echo "ACR Name: ${{ vars.ACR_NAME }}"
          echo "Environment: shared"

  no-changes-summary:
    name: 'No Changes Required'
    runs-on: ubuntu-latest
    needs: what-if-analysis
    if: needs.what-if-analysis.outputs.has-changes == 'false'
    steps:
      - name: 'Summary'
        run: |
          echo "✅ Infrastructure is already up to date!"          
          echo "No changes detected in what-if analysis."
          echo "ACR Name: ${{ vars.ACR_NAME }}"
          echo "Environment: shared"
