name: "Backend CI Pipeline"
on: 
  push:
    branches:
      - '**'
    paths:
      - 'backend/**'

  pull_request:
    branches:
      - 'main'
    paths:
      - 'backend/**'
jobs:
  check_changes:
    name: 'Check for file changes'
    runs-on: ubuntu-latest
    outputs:
      sca_scan_required: ${{ steps.changed-file-requirements.outputs.any_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for changed-files to work properly
      
      - uses: tj-actions/changed-files@v44 # Use a specific version for stability
        id: changed-file-requirements
        with:
          # We tell the action to ONLY look for changes in this specific file.
          files: backend/requirements.txt

  static_analysis:
    name: 'Static Analysis (SAST Scan)'
    uses: ./.github/workflows/reusable-sast-scan.yml
    with:
      language: 'python'
  sca_analysis:
    name: 'Software Composition Analysis (SCA Scan)'
    needs: check_changes
    if: needs.check_changes.outputs.sca_scan_required == 'true'
    uses: ./.github/workflows/reusable-sca-scan.yml
    with:
      paths: 'backend/requirements.txt'
  container_analysis:
    name: 'Container Analyis (Dockerfile Scan, Container Scan, Container build)'
    needs: check_changes
    uses: ./.github/workflows/reusable-container-scan.yml
    with:
      path: 'backend/Dockerfile'
      container-name: 'backend-app'