# .github/workflows/reusable-build-push.yml

name: 'Reusable - Build and Push to ACR'

on:
  workflow_call:
    inputs:
      dockerfile-path:
        required: true
        type: string
        description: 'Path to the Dockerfile'
      image-name:
        required: true
        type: string
        description: 'Name for the container image (e.g., backend-app)'
      build-context:
        required: true
        type: string
        description: 'Build context for the Docker build (e.g., ./backend)'
      acr-name:
        required: true
        type: string
        description: 'Name of the Azure Container Registry'
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    environment: 'shared'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get ACR access token
        id: acr_token
        run: |
          ACR_TOKEN=$(az acr login --name ${{ inputs.acr-name }} --expose-token --output tsv --query accessToken)
          echo "token=${ACR_TOKEN}" >> $GITHUB_OUTPUT

      - name: Log in to Docker with new token
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.acr-name }}.azurecr.io
          username: 00000000-0000-0000-0000-000000000000
          password: ${{ steps.acr_token.outputs.token }}